# Copyright The hcmus team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is Conda environment file
# Usage: `conda env update -f environment.yml`

name: emb

channels:
    - pytorch
    - huggingface
    - conda-forge

dependencies:
    # --- required ---
    - cudatoolkit=11.6
    - pytorch=1.12.0
    - python=3.10
    - transformers>=4.35.0
    - mkl==2024.0
    # https://github.com/pytorch/pytorch/issues/123097#issuecomment-2095228569
    # --- nlp ---
    - tokenizers
    - sentencepiece
    - sentence-transformers
    - langdetect
    # haystack
    - haystack-ai
    - chroma-haystack
    # --- utils ---
    - pandas
    - numpy
    - tqdm
